/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 * 
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    xml?: string;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    author?: string;
}

/**
 * Check if a given object implements the Assignment interface.
 */
export function instanceOfAssignment(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentFromJSON(json: any): Assignment {
    return AssignmentFromJSONTyped(json, false);
}

export function AssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'xml': !exists(json, 'xml') ? undefined : json['xml'],
        'author': !exists(json, 'author') ? undefined : json['author'],
    };
}

export function AssignmentToJSON(value?: Assignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
        'xml': value.xml,
        'author': value.author,
    };
}

