/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';
import type {Assignment} from './Assignment';
import {AssignmentFromJSON, AssignmentToJSON,} from './Assignment';
import type {Exam} from './Exam';
import {ExamFromJSON, ExamToJSON,} from './Exam';

/**
 * 
 * @export
 * @interface ExamSubmission
 */
export interface ExamSubmission {
    /**
     * 
     * @type {string}
     * @memberof ExamSubmission
     */
    id?: string;
    /**
     * 
     * @type {Exam}
     * @memberof ExamSubmission
     */
    exam?: Exam;
    /**
     * 
     * @type {Assignment}
     * @memberof ExamSubmission
     */
    assignment?: Assignment;
    /**
     * 
     * @type {string}
     * @memberof ExamSubmission
     */
    xml?: string;
    /**
     * 
     * @type {Date}
     * @memberof ExamSubmission
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExamSubmission
     */
    submittedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExamSubmission
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof ExamSubmission
     */
    examSubmissionState?: ExamSubmissionExamSubmissionStateEnum;
}


/**
 * @export
 */
export const ExamSubmissionExamSubmissionStateEnum = {
    Draft: 'Draft',
    Submitted: 'Submitted',
    Graded: 'Graded'
} as const;
export type ExamSubmissionExamSubmissionStateEnum = typeof ExamSubmissionExamSubmissionStateEnum[keyof typeof ExamSubmissionExamSubmissionStateEnum];


/**
 * Check if a given object implements the ExamSubmission interface.
 */
export function instanceOfExamSubmission(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExamSubmissionFromJSON(json: any): ExamSubmission {
    return ExamSubmissionFromJSONTyped(json, false);
}

export function ExamSubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamSubmission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'exam': !exists(json, 'exam') ? undefined : ExamFromJSON(json['exam']),
        'assignment': !exists(json, 'assignment') ? undefined : AssignmentFromJSON(json['assignment']),
        'xml': !exists(json, 'xml') ? undefined : json['xml'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (new Date(json['startedAt'])),
        'submittedAt': !exists(json, 'submittedAt') ? undefined : (new Date(json['submittedAt'])),
        'author': !exists(json, 'author') ? undefined : json['author'],
        'examSubmissionState': !exists(json, 'examSubmissionState') ? undefined : json['examSubmissionState'],
    };
}

export function ExamSubmissionToJSON(value?: ExamSubmission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'exam': ExamToJSON(value.exam),
        'assignment': AssignmentToJSON(value.assignment),
        'xml': value.xml,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt.toISOString()),
        'submittedAt': value.submittedAt === undefined ? undefined : (value.submittedAt.toISOString()),
        'author': value.author,
        'examSubmissionState': value.examSubmissionState,
    };
}

