/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 * 
 * @export
 * @interface ExamSubmissionCheckpointCommand
 */
export interface ExamSubmissionCheckpointCommand {
    /**
     * 
     * @type {string}
     * @memberof ExamSubmissionCheckpointCommand
     */
    xml?: string;
}

/**
 * Check if a given object implements the ExamSubmissionCheckpointCommand interface.
 */
export function instanceOfExamSubmissionCheckpointCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExamSubmissionCheckpointCommandFromJSON(json: any): ExamSubmissionCheckpointCommand {
    return ExamSubmissionCheckpointCommandFromJSONTyped(json, false);
}

export function ExamSubmissionCheckpointCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamSubmissionCheckpointCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xml': !exists(json, 'xml') ? undefined : json['xml'],
    };
}

export function ExamSubmissionCheckpointCommandToJSON(value?: ExamSubmissionCheckpointCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xml': value.xml,
    };
}

