/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 * 
 * @export
 * @interface ExamSubmissionSubmitCommand
 */
export interface ExamSubmissionSubmitCommand {
    /**
     * 
     * @type {string}
     * @memberof ExamSubmissionSubmitCommand
     */
    xml?: string;
}

/**
 * Check if a given object implements the ExamSubmissionSubmitCommand interface.
 */
export function instanceOfExamSubmissionSubmitCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExamSubmissionSubmitCommandFromJSON(json: any): ExamSubmissionSubmitCommand {
    return ExamSubmissionSubmitCommandFromJSONTyped(json, false);
}

export function ExamSubmissionSubmitCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamSubmissionSubmitCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'xml': !exists(json, 'xml') ? undefined : json['xml'],
    };
}

export function ExamSubmissionSubmitCommandToJSON(value?: ExamSubmissionSubmitCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'xml': value.xml,
    };
}

