/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentAssignmentDTO
 */
export interface StudentAssignmentDTO {
    /**
     * 
     * @type {string}
     * @memberof StudentAssignmentDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentAssignmentDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentAssignmentDTO
     */
    description?: string;
}

/**
 * Check if a given object implements the StudentAssignmentDTO interface.
 */
export function instanceOfStudentAssignmentDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentAssignmentDTOFromJSON(json: any): StudentAssignmentDTO {
    return StudentAssignmentDTOFromJSONTyped(json, false);
}

export function StudentAssignmentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentAssignmentDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function StudentAssignmentDTOToJSON(value?: StudentAssignmentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'description': value.description,
    };
}

